### ISSUE TITLE
Eye patch is not drawn over right eye on some devices

### ISSUE THREAD

**Issue by alexdennis** [moyheen/face-detector#2]
When testing app on my Nexus 6P I noticed that the eye patch was not properly centered over the right eye. I am guessing this is because the x and y offsets are hard coded.

A potential solution is to use scaled height and width from bitmap adjusted to the canvas

**Comment by moyheen** [comment]
Thanks! I was expecting some issues from hardcoding those values. The app was just to show what's possible with the APIs so I initially didn't give that much concern. I will explore that in future commits.
